<a href="https://colab.research.google.com/github/fxmike/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np

1D

In [53]:
x = np.array([1,3])

In [54]:
print(x)

[1 3]


In [55]:
type(x)

numpy.ndarray

In [56]:
x.ndim

1

In [57]:
x.shape

(2,)

In [58]:
x.size

2

In [59]:
x.dtype

dtype('int64')

In [60]:
x = np.array([1.3,2.3,1.4])

In [61]:
print(x)

[1.3 2.3 1.4]


In [62]:
x.dtype

dtype('float64')

2D

In [63]:
x = np.array([[1,2], [-3,1]])

In [64]:
x.ndim

2

In [65]:
x.shape

(2, 2)

In [66]:
x.dtype

dtype('int64')

In [67]:
x = np.array([[1,2,4], [4,2,1]])

In [68]:
x.shape

(2, 3)

3D

In [69]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     [[4,1,3],
      [4,2,1]]]
)

In [70]:
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [71]:
x.ndim

3

In [72]:
x.shape

(2, 2, 3)

typy danych

In [73]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [74]:
A = np.array([1.1,2.2,3.1])
A.dtype

dtype('float64')

In [75]:
A = np.array([1,2,3], dtype='float')
A

array([1., 2., 3.])

In [76]:
A = np.array([1,2,3], dtype='complex')
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [77]:
A = np.array([1.1,2.2,3.1], dtype='int')
A

array([1, 2, 3])

In [78]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [79]:
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [80]:
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

tworzenie tablic

In [81]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [82]:
np.zeros(shape=(4,10), dtype='int')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [83]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [85]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [86]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [87]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [89]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [91]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [92]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [93]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [95]:
A.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

podstawowe operacje na tablicach

In [96]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

In [97]:
A

array([3, 1, 4, 2])

In [98]:
B

array([ 3, -1,  3,  2])

In [99]:
A + B

array([6, 0, 7, 4])

In [100]:
A - B

array([0, 2, 1, 0])

In [101]:
A * B

array([ 9, -1, 12,  4])

In [102]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [103]:
A + 3

array([6, 4, 7, 5])

In [104]:
2 * A

array([6, 2, 8, 4])

In [105]:
A + 3*B

array([12, -2, 13,  8])

In [106]:
np.add(A, B)

array([6, 0, 7, 4])

In [108]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [109]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [110]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [111]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])

In [112]:
X * Y

array([[6, 0],
       [2, 0]])

In [113]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [114]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [115]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [116]:
Y @ X

array([[ 6, 18],
       [-5, -3]])

mnożenie macierzy nie jest przemienne

generowanie liczb pseudolosowych

In [117]:
np.random.seed(0)

In [121]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [122]:
np.random.rand()

0.1965823616800535

In [124]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [127]:
np.random.randint(10)

3

In [129]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [134]:
np.random.choice([4,2,1,2])

1

In [135]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [136]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.random.shuffle(data)

In [138]:
data

array([7, 2, 1, 6, 0, 5, 9, 3, 4, 8])

podstawowe funkcje

In [140]:
np.exp(1)

2.718281828459045

In [141]:
np.sqrt(9)

3.0

In [144]:
np.all([2, 1, 1])

True

In [146]:
np.any([2, 0, 1])

True

In [148]:
A = np.random.rand(5)
A

array([0.88173536, 0.69253159, 0.72525428, 0.50132438, 0.95608363])

In [149]:
np.argmax(A)

4

In [150]:
A[np.argmax(A)]

0.9560836347232239

In [151]:
np.argmin(A)

3

In [152]:
np.argsort(A)

array([3, 1, 2, 0, 4])

In [153]:
A[np.argsort(A)]

array([0.50132438, 0.69253159, 0.72525428, 0.88173536, 0.95608363])

In [154]:
np.max(A)

0.9560836347232239

In [155]:
np.min(A)

0.5013243819267023

In [156]:
np.mean(A)

0.751385849680437

In [157]:
np.median(A)

0.7252542798196405

In [158]:
np.std(A)

0.15847371958621503

indeksowanie i wycinanie

In [160]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [161]:
A[2]

2

In [162]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [163]:
A[:2]

array([0, 1])

In [164]:
A[[0,2]]

array([0, 2])

In [165]:
A[-1]

19

In [167]:
A[10:15]

array([10, 11, 12, 13, 14])

In [171]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [172]:
A[1]

array([5, 6, 7, 8, 9])

In [174]:
A[:, 1]

array([ 1,  6, 11, 16])

In [175]:
A[:, -2]

array([ 3,  8, 13, 18])

In [176]:
A[1,1]

6

In [177]:
A[1,3]

8

In [178]:
A[1:3,  1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [179]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

iteracja po tablicach, zmiana rozmiaru tablic, maski logiczne

In [180]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [183]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [184]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [186]:
A.shape

(4, 5)

In [187]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [188]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [189]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [191]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [192]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [196]:
A = np.arange(start=-10, stop= 10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [197]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [198]:
A[(A > -5) & (A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [200]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [201]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])