<a href="https://colab.research.google.com/github/fxmike/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

norma wektora, długość wektora w R2

In [32]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [33]:
np.linalg.norm(v1)

4.123105625617661

norma euklidesowa w R2

In [34]:
v2 = np.array([-10,10,13])

In [35]:
np.linalg.norm(v2)

19.209372712298546

odległość dwóch punktów na płaszczyźnie

In [36]:
p = np.array([3,0])
q = np.array([0,4])

In [37]:
np.linalg.norm(p-q)

5.0

In [38]:
p = np.array([3,0,1])
q = np.array([0,4,2])

In [39]:
np.linalg.norm(p-q)

5.0990195135927845

mnożenie macierzy

In [40]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])

In [41]:
X

array([[5, 3],
       [3, 9]])

In [42]:
Y

array([[ 1],
       [-1]])

In [43]:
Z = np.dot(X,Y)

In [44]:
Z

array([[ 2],
       [-6]])

In [45]:
Z.shape

(2, 1)

In [46]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y= np.array([[2, 1, -1],
             [0, -1, 2],
              [3, 2, 0]])

In [47]:
X

array([[ 2, -1,  3],
       [ 3,  1,  0]])

In [48]:
Y

array([[ 2,  1, -1],
       [ 0, -1,  2],
       [ 3,  2,  0]])

In [49]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

wyznacznik macierzy

In [50]:
A = np.array([[2,4], [-1,3]])

In [51]:
round(np.linalg.det(A))

10

ślad macierzy - suma przekątnych

In [52]:
A = np.array([[2,4], [-1,3]])

In [53]:
np.trace(A)

5

macierz jednostkowa

In [54]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

macierz odwrotna

In [55]:
A

array([[ 2,  4],
       [-1,  3]])

In [56]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [57]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [58]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

macierz transponowana

In [59]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [60]:
A.T

array([[ 2, -1],
       [ 4,  3]])

rozwiązywanie układów równań

In [61]:
A = np.array([[2,4], [1,-1]])

In [62]:
A

array([[ 2,  4],
       [ 1, -1]])

In [68]:
B = np.array([[10], [-1]])

In [69]:
B

array([[10],
       [-1]])

In [70]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

In [71]:
X

array([[1.],
       [2.]])