<a href="https://colab.research.google.com/github/fxmike/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd

In [5]:
price = np.array([[12.4, 12.8, 11.9, 12.6, 1000],
                  [12.5, 13.00, 11.7, 12.2, 2000],
                  [12.2, 13.4, 12.2, 13.2, 1500]])
price

array([[  12.4,   12.8,   11.9,   12.6, 1000. ],
       [  12.5,   13. ,   11.7,   12.2, 2000. ],
       [  12.2,   13.4,   12.2,   13.2, 1500. ]])

In [6]:
price.sum()

4650.1

In [10]:
price[:,0].sum(axis=0).round(2)

37.1

In [11]:
np.sum(price)

4650.1

In [13]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [14]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [15]:
np.median(price)

12.6

In [16]:
np.mean(price)

310.0066666666667

In [17]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [18]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

In [19]:
X = np.array([2., -3, 4])
print(X.dtype)

float64


In [38]:
np.random.randn(10)


array([-0.24669112, -1.93681858, -1.48176948, -0.87246973, -1.65622055,
       -0.97103815,  0.72145205,  0.91121628,  0.62661573,  0.22563169])

In [48]:
A = np.random.rand(6).reshape(2,3)

In [49]:
A

array([[0.84140001, 0.05575551, 0.81793018],
       [0.42216391, 0.37144866, 0.31929849]])

In [53]:
B = np.random.rand(3).reshape(3,1)
B

array([[0.04850628],
       [0.36976721],
       [0.25968874]])

In [55]:
np.dot(A,B)

array([[0.273837  ],
       [0.24074536]])